const MAX_LIKE_MOVIES_LENGTH = 4;
const DELAY_VIDEO = 1000;
const DEFAULT_MOVIES_COUNT = 8;
const DEFAULT_PAGE = 1;
const DEFAULT_TIMEOUT = 5000;

const DEFAULT_GENRE = `All genres`;
const BACKEND_URL = `https://6.react.pages.academy/wtw`;

export {
  MAX_LIKE_MOVIES_LENGTH,
  DELAY_VIDEO,
  DEFAULT_MOVIES_COUNT,
  DEFAULT_PAGE,
  DEFAULT_TIMEOUT,
  DEFAULT_GENRE,
  BACKEND_URL
};
